# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/sonnet': '@stable'
    'frameworks/kwidgetaddons': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/kemoticons': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/knotifyconfig': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kpeople': '@stable'
    'network/ktp-common-internals': '@same'
