[Desktop Entry]
Name=OTR
Name[cs]=OTR
Name[de]=OTR
Name[fr]=OTR
Name[nb]=OTR
Name[nl]=OTR
Name[pt]=OTR
Name[sk]=OTR
Name[sv]=OTR
Name[uk]=OTR
Name[x-test]=xxOTRxx
Comment=If a message is an OTR message, it will not be shown
Comment[cs]=Pokud je zpráva OTR, nebude zobrazena
Comment[de]=Wenn eine Nachricht vom Typ OTR ist, wird sie nicht angezeigt
Comment[fr]=Si un message est un message OTR, il ne sera pas affiché
Comment[nl]=Als een bericht een OTR-bericht is zal het niet getoond worden
Comment[pt]=Se uma dada mensagem for em OTR, não será apresentada
Comment[sk]=Ak správa je OTR správa, nebude zobrazená
Comment[sv]=Om ett meddelande är ett OTR-meddelande, kommer det inte att visas
Comment[uk]=Якщо повідомлення є повідомленням OTR, його не буде показано
Comment[x-test]=xxIf a message is an OTR message, it will not be shownxx
Encoding=UTF-8
Type=Service
ServiceTypes=KTpTextUi/MessageFilter

X-KDE-Library=ktptextui_message_filter_otr
X-KDE-PluginInfo-Author=Marcin Ziemiński
X-KDE-PluginInfo-Email=zieminn@gmail.com
X-KDE-PluginInfo-Name=otr
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@
