[Desktop Entry]
Encoding=UTF-8
Name=Short URLs
Name[bs]=Kratke URL adrese
Name[ca]=URL breus
Name[cs]=Krátké URL
Name[de]=Kurz-URLs
Name[fr]=URL réduites
Name[it]=URL brevi
Name[kk]=Қысқа URL-дер
Name[nl]=Korte URL's
Name[pt_BR]=URLs curtas
Name[sk]=Krátke URL
Name[sv]=Korta webbadresser
Name[uk]=Короткі адреси
Name[x-test]=xxShort URLsxx
Comment=Shows the actual URL to which a shortened URL is redirecting to
Comment[bs]=Prikazuje stvarni URL na koji je skraćeni preusmjeren
Comment[ca]=Mostra l'URL real al que es redirigeix un URL breu
Comment[cs]=Zobrazí skutečné URL, na které je přesměrováno zkrácené URL
Comment[de]=Zeigt die tatsächliche Adresse (URL), auf die eine gekürzte URL umgeleitet wird
Comment[fr]=Affiche l'URL courante vers laquelle pointe une URL réduite
Comment[it]=Mostra l'URL vero a cui si viene rediretti da un URL abbreviato
Comment[kk]=Қысқа URL бағыттайтын шын URL-адресін көрсету
Comment[nl]=Toont de actuele URL waarnaar de korte URL verwijst
Comment[pt_BR]=Mostra a URL real para onde direciona uma URL curta
Comment[sk]=Zobrazí aktuálne URL, na ktoré je presmerované skrátené URL
Comment[sv]=Visar den verkliga webbadressen som en avkortad webbadress leder till
Comment[uk]=Показує справжню адресу, до якої переспрямовуватиме вас скорочена адреса
Comment[x-test]=xxShows the actual URL to which a shortened URL is redirecting toxx
Type=Service
ServiceTypes=KTpTextUi/MessageFilter
X-KDE-Library=ktptextui_message_filter_urlexpansion
X-KDE-PluginInfo-Author=Anant Kamath
X-KDE-PluginInfo-Email=kamathanant@gmail.org
X-KDE-PluginInfo-Name=urlexpansion
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=LGPL
X-KDE-PluginInfo-EnabledByDefault=true
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@
