[Desktop Entry]
Encoding=UTF-8
Name=Bugzilla Information
Name[el]=Πληροφορίες Bugzilla
Name[ia]=Information de Bugzilla
Name[it]=Informazioni di Bugzilla
Name[nl]=Informatie in Bugzilla
Name[pt]=Informação do Bugzilla
Name[pt_BR]=Informações do Bugzilla
Name[sk]=Informácie o Bugzilla
Name[sl]=Podrobnosti o Bugzilli
Name[sr]=Бубаждајини подаци
Name[sr@ijekavian]=Бубаждајини подаци
Name[sr@ijekavianlatin]=Bubaždajini podaci
Name[sr@latin]=Bubaždajini podaci
Name[tr]=Bugzilla Bilgisi
Name[uk]=Дані у системі стеження за вадами
Name[x-test]=xxBugzilla Informationxx
Name[zh_TW]=Bugzilla 資訊
Comment=When receiving a link to a bug on bugzilla show additional information such as the title and status
Comment[el]=Κατά τη λήψη συνδέσμου σε ένα σφάλμα στο bugzilla να εμφανίζοντια επιπλέον πληροφορίες όπως ο τίτλος και η κατάσταση
Comment[ia]=Quando on recip eun ligamine a un bug sur bugzilla on monstra information additional tal como le titulo e le stato
Comment[it]=Con collegamenti a bugzilla, mostra informazioni quali il titolo e lo stato dei bug relativi
Comment[nl]=Bij het ontvangen van een koppeling naar een bug in bugzilla toon dan extra informatie zoals de titel en de status
Comment[pt]=Ao receber uma hiperligação para um erro no Bugzilla, mostra informações adicionais como o título e o estado
Comment[pt_BR]=Mostra informações adicionais ao receber um link para um erro no Bugzilla, como o título e o status
Comment[sk]=Pri prijatí odkazu na chybu na Bugzille zobraziť dodatočné informácie ako titul a stav
Comment[sl]=Ko prejmete povezavo na hrošč na Bugzilli, prikaže dodatne podrobnosti kot recimo naslov in stanje
Comment[sr]=Додатни подаци при пријему везе до грешке са Бубаждаје, попут наслова и стања
Comment[sr@ijekavian]=Додатни подаци при пријему везе до грешке са Бубаждаје, попут наслова и стања
Comment[sr@ijekavianlatin]=Dodatni podaci pri prijemu veze do greške sa Bubaždaje, poput naslova i stanja
Comment[sr@latin]=Dodatni podaci pri prijemu veze do greške sa Bubaždaje, poput naslova i stanja
Comment[tr]=Bugzilla'daki bir hataya bağlantı alırken, başlık ve durum gibi ek bilgileri göster
Comment[uk]=У разі отримання посилання на запис вади у системі стеження за вадами показати додаткові дані, зокрема назву запису та стан вади
Comment[x-test]=xxWhen receiving a link to a bug on bugzilla show additional information such as the title and statusxx
Comment[zh_TW]=接收到 bugzilla 上的連結時，顯示額外的資訊，如標題與狀態等
Type=Service
ServiceTypes=KTpTextUi/MessageFilter
X-KDE-Library=ktptextui_message_filter_bugzilla
X-KDE-PluginInfo-Author=KDE Telepathy Developers
X-KDE-PluginInfo-Email=kde-telepathy@kde.org
X-KDE-PluginInfo-Name=bugzilla
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=LGPL
X-KDE-PluginInfo-EnabledByDefault=true
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@
