[Desktop Entry]
Encoding=UTF-8
Type=Service
ServiceTypes=KTpTextUi/MessageFilter

X-KDE-Library=ktptextui_message_filter_geopoint
X-KDE-PluginInfo-Author=Alexandr Akulich
X-KDE-PluginInfo-Email=akulichalexander@gmail.com
X-KDE-PluginInfo-Name=geopoint
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=false
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@

Name=Geopoint Preview
Name[ca]=Vista prèvia del punt geogràfic
Name[ca@valencia]=Vista prèvia del punt geogràfic
Name[es]=Vista previa de punto geográfico
Name[nl]=Voorbeeld van geo-punt
Name[pl]=Podgląd geopunktu
Name[pt]=Antevisão de Ponto Geográfico
Name[sk]=Náhľad Geopoint
Name[sl]=Predogled Geopoint
Name[sv]=Förhandsgranskning av geografisk punkt
Name[uk]=Перегляд геоточки
Name[x-test]=xxGeopoint Previewxx
Comment=Show geo URI on a map view.
Comment[ca]=Mostra la URI geogràfica a la vista d'un mapa.
Comment[ca@valencia]=Mostra la URI geogràfica a la vista d'un mapa.
Comment[es]=Mostrar un URI geográfico en un visor de mapa.
Comment[nl]=Geo-URI op een kaart tonen.
Comment[pl]=Pokaż URI geo w widoku mapy.
Comment[pt]=Mostrar um URI geográfico num mapa.
Comment[sk]=Zobraziť geo URI na pohľade mapy.
Comment[sl]=Pokaži geo URI na prikazu zemljevida.
Comment[sv]=Visa geografisk webbadress i en kartvy.
Comment[uk]=Показувати геоадресу на перегляді карти.
Comment[x-test]=xxShow geo URI on a map view.xx
