[Desktop Entry]
Encoding=UTF-8
Name=Text Formatting
Name[cs]=Formátování textu
Name[de]=Textformatierung
Name[el]=Διαμόρφωση κειμένου
Name[fi]=Tekstin muotoilu
Name[ia]=Dar forma a texto
Name[it]=Formattazione del testo
Name[nl]=Tekstopmaak
Name[pt]=Formatação do Texto
Name[pt_BR]=Formatação do texto
Name[sk]=Formátovanie textu
Name[sl]=Oblikovanje besedila
Name[uk]=Форматування тексту
Name[x-test]=xxText Formattingxx
Comment=Use /, _, * and - to make text italic, underlined, bold or strikeout respectively
Comment[cs]=Použít /,_, * a - pro kurzívu, podtržený, tučný a přeškrtnutý text
Comment[de]=Mit „/“, „_“, “*“ und „-“ wird Text geneigt, unterstrichen, fett oder durchgestrichen dargestellt
Comment[el]=Χρησιμοποιήστε /, _, * και - για πλάγιους, υπογραμμισμένους, έντονους ή με επιγράμμιση χαρακτήρες αντίστοιχα
Comment[ia]=Usa /,_,* e - pro facer texto cursive, sublineate, grasse o strikeout respectivemente
Comment[it]=Usa /, _, * e - per rendere il testo rispettivamente corsivo, sottolineato, grassetto o barrato
Comment[nl]=Gebruik /, _, * en - om tekst respectievelijk cursief, onderstreept, vet of doorgestreept te maken
Comment[pt]=Usar o '/', '_', '*' e '-' para tornar o texto itálico, sublinhado, negrito ou traçado, respectivamente
Comment[pt_BR]=Use /, _, * e - para tornar o texto em itálico, sublinhado, negrito ou tachado, respectivamente
Comment[sk]=Použite /,  _, * a - na zmenu textu na kurzívu, podčiarknuté, tučné alebo prečiarknuté
Comment[sl]=Uporabite /,_, * in -, da bo besedilo ležeče, podčrtano, krepko ali prečrtano
Comment[uk]=Використовувати /, _, * і - для курсиву, підкресленого, напівжирного та перекресленого тексту, відповідно
Comment[x-test]=xxUse /, _, * and - to make text italic, underlined, bold or strikeout respectivelyxx
Type=Service
ServiceTypes=KTpTextUi/MessageFilter
X-KDE-Library=ktptextui_message_filter_formatting
X-KDE-PluginInfo-Author=KDE Telepathy Developers
X-KDE-PluginInfo-Email=kde-telepathy@kde.org
X-KDE-PluginInfo-Name=formatting
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=false
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@
