[Desktop Entry]
Encoding=UTF-8
Type=Service
ServiceTypes=KTpTextUi/MessageFilter

X-KDE-Library=ktptextui_message_filter_latex
X-KDE-PluginInfo-Author=Lasath Fernando
X-KDE-PluginInfo-Email=kde@lasath.org
X-KDE-PluginInfo-Name=latex
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=false
X-KDE-PluginInfo-Weight=10
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@

Name=LaTeX Renderer
Name[bs]=LaTeX Obrađivač
Name[ca]=Renderitzador LaTeX
Name[de]=LaTeX-Renderer
Name[fr]=Moteur de rendu LaTeX
Name[it]=Visualizzatore LaTeX
Name[kk]=LaTeX кескіндегіші
Name[nl]=LaTeX-renderer
Name[pt_BR]=Renderizador de LaTeX
Name[sv]=Latex-återgivning
Name[uk]=Показ формул LaTeX
Name[x-test]=xxLaTeX Rendererxx
Comment=If incoming messages contain LaTeX between $$, it will render it directly into the chat.
Comment[bs]=Ako poruka sadrži Latex između $$, ona će se ugraditi u ćaskanje.
Comment[ca]=Si els missatges entrants conten LaTeX entre $$, es representarà directament en el xat.
Comment[de]=Wenn eine eingehende Nachricht LaTeX eingeschlossenen in $$ enthält, wird sie direkt im Chat-Fenster gerendert.
Comment[fr]=Si des messages entrants contiennent du LaTeX entre « $$ », il le rendra directement dans le forum de discussions.
Comment[it]=Se in un messaggio c'è codice LaTeX dentro $$...$$, sarà visualizzato direttamente nella finestra di chat
Comment[kk]=Егер кіріс хабарламада $$ де қоршалған LaTex болса, ол чатта тікелей кескінделеді.
Comment[nl]=Als een inkomend bericht LaTeX tussen $$ bevat, zal het direct in de chat worden weergegeven
Comment[pt_BR]=Se existir código em LaTeX entre $$ nas mensagens recebidas, ele será mostrado no bate-papo.
Comment[sv]=Om inkommande meddelande innehåller Latex mellan $$, återges den direkt i chatten.
Comment[uk]=Якщо у будь-якому з повідомлень містяться формули LaTeX, обмежені символами $$, їхнє зображення буде вбудовано безпосередньо до панелі спілкування.
Comment[x-test]=xxIf incoming messages contain LaTeX between $$, it will render it directly into the chat.xx
