[Desktop Entry]
Name=Web Shortcuts
Name[bs]=Web prečice
Name[ca]=Dreceres web
Name[ca@valencia]=Dreceres web
Name[cs]=Webové zkratky
Name[da]=Webgenveje
Name[de]=Webkürzel
Name[el]=Συντομεύσεις ιστού
Name[es]=Accesos rápidos a la web
Name[et]=Veebikiirkorraldused
Name[fi]=WWW-pikavalinnat
Name[fr]=Raccourcis web
Name[ga]=Aicearraí Gréasáin
Name[gl]=Atallos web
Name[hu]=Keresőazonosítók
Name[ia]=Vias Breve de web
Name[it]=Scorciatoie web
Name[kk]=Веб қысқартулары
Name[lt]=Žiniatinklio nuorodos
Name[nb]=Nettsnarveier
Name[nl]=Webkoppelingen
Name[nn]=Vevsnarvegar
Name[pl]=Skróty sieciowe
Name[pt]=Atalhos Web
Name[pt_BR]=Atalhos da Internet
Name[ro]=Acceleratori web
Name[ru]=Web-сокращения
Name[se]=Fierpmádatlávkestagat
Name[sk]=Webové skratky
Name[sl]=Spletne bližnjice
Name[sr]=Веб пречице
Name[sr@ijekavian]=Веб пречице
Name[sr@ijekavianlatin]=Veb prečice
Name[sr@latin]=Veb prečice
Name[sv]=Webbgenvägar
Name[tr]=Web Kısa Yolları
Name[uk]=Вебскорочення
Name[wa]=Rascourtis waibe
Name[x-test]=xxWeb Shortcutsxx
Name[zh_CN]=网页快捷方式
Name[zh_TW]=網頁捷徑
Encoding=UTF-8
Type=Service
Comment=Expand a KDE-shortened URI into a URL (i.e. typing wp:KDE will translate to http://en.wikipedia.org/wiki/KDE)
Comment[ia]=Expande un URI abbreviate de KDE in un URL (i.e. typar wp:KDE il traducera se mesme in http://en.wikipedia.org/wiki/KDE)
Comment[it]=Espande un URI abbreviato di KDE in un URL (ad es. wp:KDE sarà trasformato in http://it.wikipedia.org/wiki/KDE)
Comment[nl]=Expandeer een door KDE afgekorte URI in een URL (bijv. typen van wp:KDE wordt vertaald in http://en.wikipedia.org/wiki/KDE)
Comment[pt]=Expandir um URI curto no KDE para um URL (i.e., se escrever wp:KDE, será traduzido para http://en.wikipedia.org/wiki/KDE)
Comment[pt_BR]=Expandir uma URI curta no KDE para uma URL (p.ex., se digitar wp:KDE, será traduzido para http://en.wikipedia.org/wiki/KDE)
Comment[sl]=Razširi URI, ki ga je skrajšal KDE, v naslov URL  (npr. če vtipkate wp:KDE bo to postalo http://en.wikipedia.org/wiki/KDE)
Comment[uk]=Доповнення вебскорочень адрес KDE до повноцінних адрес (тобто текст wp:KDE буде доповнено до http://en.wikipedia.org/wiki/KDE)
Comment[x-test]=xxExpand a KDE-shortened URI into a URL (i.e. typing wp:KDE will translate to http://en.wikipedia.org/wiki/KDE)xx
ServiceTypes=KTpTextUi/MessageFilter

X-KDE-Library=ktptextui_message_filter_searchexpansion
X-KDE-PluginInfo-Author=Lasath Fernando
X-KDE-PluginInfo-Email=kde@lasath.org
X-KDE-PluginInfo-Name=searchexpansion
X-KDE-PluginInfo-Version=@KTP_TEXT_UI_VERSION@
X-KDE-PluginInfo-Website=http://community.kde.org/KTp
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=false
X-KTp-PluginInfo-Version=@KTP_MESSAGE_FILTER_FRAMEWORK_VERSION@
